// <auto-generated />
namespace SystemClub.Contex
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DBClub : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBClub));
        
        string IMigrationMetadata.Id
        {
            get { return "201708091059519_DBClub"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
